/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MacButton {
        "disabled": boolean;
        "icon"?: any;
        "iconOnly": boolean;
        "size": any;
        "text": string;
        "type": any;
        "variant": any;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface MacButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMacButtonElement;
}
declare global {
    interface HTMLMacButtonElement extends Components.MacButton, HTMLStencilElement {
    }
    var HTMLMacButtonElement: {
        prototype: HTMLMacButtonElement;
        new (): HTMLMacButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "mac-button": HTMLMacButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MacButton {
        "disabled"?: boolean;
        "icon"?: any;
        "iconOnly"?: boolean;
        "onButtonClick"?: (event: MacButtonCustomEvent<MouseEvent>) => void;
        "size"?: any;
        "text": string;
        "type"?: any;
        "variant"?: any;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "mac-button": MacButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mac-button": LocalJSX.MacButton & JSXBase.HTMLAttributes<HTMLMacButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
